modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

issueTrackerURL="https://github.com/SkyNetCloud/Cobbmon-Broadcaster-Forge/issues" #optional

[[mods]] #mandatory

modId = "cobblemonbroadcast" #mandatory

version = "${file.jarVersion}" #mandatory

updateJSONURL= "https://raw.githubusercontent.com/SkyNetCloud/Cobbmon-Broadcaster-Forge/master/update.json"

logoFile="logo.png"

displayName = "cobblemonbroadcastmod" #mandatory

authors = "SkyNetCloud" #optional

description = '''
A mod that can be use to Broadcast Cobblemon Capture event for Legendarys Ultra Beasts Shinys and Normal All can be toggle on or off
'''
[[dependencies.cobblemonbroadcast]]
modId = "cobblemon" #mandatory
mandatory = true #mandatory
versionRange = "[1.2.0,)" #mandatory

[[dependencies.cobblemonbroadcast]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory

[[dependencies.cobblemonbroadcast]]
modId="architectury"
mandatory=true
versionRange="[6.0.37,)"

